const HEADLIGHTS_COMMON_CID = '_';
const HEADLIGHTS_LEGENDARY_CID = '_';
const HEADLIGHTS_RARE_CID = '_';
const RIM_COMMON_1_CID = '_';
const RIM_COMMON_2_CID = '_';
const RIM_COMMON_3_CID = '_';
const RIM_LEGENDARY_CID = '_';
const RIM_RARE_1_CID = '_';
const RIM_RARE_2_CID = '_';
const SPOILER_COMMON_1_CID = '_';
const SPOILER_COMMON_2_CID = '_';
const SPOILER_COMMON_3_CID = '_';
const SPOILER_LEGENDARY_CID = '_';
const SPOILER_RARE_1_CID = '_';
const SPOILER_RARE_2_CID = '_';
const TINTED_WINDOWS_LEGENDARY_CID = '_';
const WRAP_COMMON_1_CID = '_';
const WRAP_COMMON_2_CID = '_';
const WRAP_COMMON_3_CID = '_';
const WRAP_LEGENDARY_CID = '_';
const WRAP_RARE_1_CID = '_';
const WRAP_RARE_2_CID = '_';
module.exports = {
  HEADLIGHTS_COMMON_CID,
  HEADLIGHTS_LEGENDARY_CID,
  HEADLIGHTS_RARE_CID,
  RIM_COMMON_1_CID,
  RIM_COMMON_2_CID,
  RIM_COMMON_3_CID,
  RIM_LEGENDARY_CID,
  RIM_RARE_1_CID,
  RIM_RARE_2_CID,
  SPOILER_COMMON_1_CID,
  SPOILER_COMMON_2_CID,
  SPOILER_COMMON_3_CID,
  SPOILER_LEGENDARY_CID,
  SPOILER_RARE_1_CID,
  SPOILER_RARE_2_CID,
  TINTED_WINDOWS_LEGENDARY_CID,
  WRAP_COMMON_1_CID,
  WRAP_COMMON_2_CID,
  WRAP_COMMON_3_CID,
  WRAP_LEGENDARY_CID,
  WRAP_RARE_1_CID,
  WRAP_RARE_2_CID,
};