@startuml RemoveItemFromCar

actor User
participant "Browser: Garage"
participant Web3
participant IPFS
participant "Backend: Image-Composition"
participant "Smart Contract"

User -> "Browser: Garage": Click "Mount" btn \n{itemManagement(newItemMetadataCID, 'remove')}

"Browser: Garage" -> IPFS: ipfs.cat(itemMetadata)
IPFS --> "Browser: Garage": JSON - itemMetadataURI
"Browser: Garage" -> Web3: getCarID(account)
Web3 -> "Smart Contract": getCarCID(carID)
"Smart Contract" --> Web3: default value (0)
Web3 --> "Browser: Garage": default value (0)
"Browser: Garage" -> IPFS: ipfs.cat(carMetadata)
IPFS --> "Browser: Garage": JSON - carMetadataURI
"Browser: Garage" -> "Browser: Garage": substitute current item CID with default value
"Browser: Garage" -> IPFS: ipfs.cat of all items CID applied on the car
IPFS --> "Browser: Garage": item metadata of all applied items
"Browser: Garage" -> "Browser: Garage": collect all images CID of applied items in listItemsImageCIDs
"Browser: Garage" -> "Backend: Image-Composition": axios.get(route: create-composite)
"Backend: Image-Composition" -> "Backend: Image-Composition": Sharp - canvas.composite(layers)
"Backend: Image-Composition" --> "Browser: Garage": new merged image (base64 encoded)
"Browser: Garage" -> IPFS: ipfs.add(newMergedImage)
IPFS --> "Browser: Garage": CID - newMergedImage
"Browser: Garage" -> IPFS: ipfs.pin.rm(oldCarImageCID)
IPFS --> "Browser: Garage": operation status code
"Browser: Garage" -> IPFS: ipfs.add(newCarMetadata)
IPFS --> "Browser: Garage": CID - newCarMetadataCID
"Browser: Garage" -> IPFS: ipfs.pin.rm(oldCarMetadataCID)
IPFS --> "Browser: Garage": operation status code
"Smart Contract" --> Web3: currentContractNonce
Web3 --> "Browser: Garage": currentContractNonce
"Browser: Garage" -> Web3: setCarCID(carID, newCarMetadataCID) {from: contract, nonce: currentContractNonce}
Web3 -> "Smart Contract": setCarCID(carID, newCarMetadataCID) {from: contract, nonce: currentContractNonce}

alt successfull setCarCID transaction
    "Smart Contract" --> Web3: Transaction Succeeded
    Web3 --> "Browser: Garage": Transaction Succeeded
    "Browser: Garage" --> User: Show in "MyCar" the new generated car \nUpdate applied/not-applied items columns
 
else failed setCarCID transaction      
    "Smart Contract" --> Web3: error
    Web3 --> "Browser: Garage": error
    "Browser: Garage" --> User: error
    end


@enduml
